# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/203/bin/cmake

# The command to remove a file.
RM = /snap/cmake/203/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/caslarui/POO/C++/LOOP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/caslarui/POO/C++/LOOP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/203/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/203/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/caslarui/POO/C++/LOOP/CMakeFiles /home/caslarui/POO/C++/LOOP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/caslarui/POO/C++/LOOP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LOOP

# Build rule for target.
LOOP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LOOP
.PHONY : LOOP

# fast build rule for target.
LOOP/fast:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/build
.PHONY : LOOP/fast

Game/Characters/Attributes/Coords.o: Game/Characters/Attributes/Coords.cpp.o

.PHONY : Game/Characters/Attributes/Coords.o

# target to build an object file
Game/Characters/Attributes/Coords.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Coords.cpp.o
.PHONY : Game/Characters/Attributes/Coords.cpp.o

Game/Characters/Attributes/Coords.i: Game/Characters/Attributes/Coords.cpp.i

.PHONY : Game/Characters/Attributes/Coords.i

# target to preprocess a source file
Game/Characters/Attributes/Coords.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Coords.cpp.i
.PHONY : Game/Characters/Attributes/Coords.cpp.i

Game/Characters/Attributes/Coords.s: Game/Characters/Attributes/Coords.cpp.s

.PHONY : Game/Characters/Attributes/Coords.s

# target to generate assembly for a file
Game/Characters/Attributes/Coords.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Coords.cpp.s
.PHONY : Game/Characters/Attributes/Coords.cpp.s

Game/Characters/Attributes/Effects.o: Game/Characters/Attributes/Effects.cpp.o

.PHONY : Game/Characters/Attributes/Effects.o

# target to build an object file
Game/Characters/Attributes/Effects.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Effects.cpp.o
.PHONY : Game/Characters/Attributes/Effects.cpp.o

Game/Characters/Attributes/Effects.i: Game/Characters/Attributes/Effects.cpp.i

.PHONY : Game/Characters/Attributes/Effects.i

# target to preprocess a source file
Game/Characters/Attributes/Effects.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Effects.cpp.i
.PHONY : Game/Characters/Attributes/Effects.cpp.i

Game/Characters/Attributes/Effects.s: Game/Characters/Attributes/Effects.cpp.s

.PHONY : Game/Characters/Attributes/Effects.s

# target to generate assembly for a file
Game/Characters/Attributes/Effects.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Effects.cpp.s
.PHONY : Game/Characters/Attributes/Effects.cpp.s

Game/Characters/Attributes/Stats.o: Game/Characters/Attributes/Stats.cpp.o

.PHONY : Game/Characters/Attributes/Stats.o

# target to build an object file
Game/Characters/Attributes/Stats.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Stats.cpp.o
.PHONY : Game/Characters/Attributes/Stats.cpp.o

Game/Characters/Attributes/Stats.i: Game/Characters/Attributes/Stats.cpp.i

.PHONY : Game/Characters/Attributes/Stats.i

# target to preprocess a source file
Game/Characters/Attributes/Stats.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Stats.cpp.i
.PHONY : Game/Characters/Attributes/Stats.cpp.i

Game/Characters/Attributes/Stats.s: Game/Characters/Attributes/Stats.cpp.s

.PHONY : Game/Characters/Attributes/Stats.s

# target to generate assembly for a file
Game/Characters/Attributes/Stats.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Stats.cpp.s
.PHONY : Game/Characters/Attributes/Stats.cpp.s

Game/Characters/Attributes/Strategy.o: Game/Characters/Attributes/Strategy.cpp.o

.PHONY : Game/Characters/Attributes/Strategy.o

# target to build an object file
Game/Characters/Attributes/Strategy.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Strategy.cpp.o
.PHONY : Game/Characters/Attributes/Strategy.cpp.o

Game/Characters/Attributes/Strategy.i: Game/Characters/Attributes/Strategy.cpp.i

.PHONY : Game/Characters/Attributes/Strategy.i

# target to preprocess a source file
Game/Characters/Attributes/Strategy.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Strategy.cpp.i
.PHONY : Game/Characters/Attributes/Strategy.cpp.i

Game/Characters/Attributes/Strategy.s: Game/Characters/Attributes/Strategy.cpp.s

.PHONY : Game/Characters/Attributes/Strategy.s

# target to generate assembly for a file
Game/Characters/Attributes/Strategy.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Attributes/Strategy.cpp.s
.PHONY : Game/Characters/Attributes/Strategy.cpp.s

Game/Characters/Heroes/Ability.o: Game/Characters/Heroes/Ability.cpp.o

.PHONY : Game/Characters/Heroes/Ability.o

# target to build an object file
Game/Characters/Heroes/Ability.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Ability.cpp.o
.PHONY : Game/Characters/Heroes/Ability.cpp.o

Game/Characters/Heroes/Ability.i: Game/Characters/Heroes/Ability.cpp.i

.PHONY : Game/Characters/Heroes/Ability.i

# target to preprocess a source file
Game/Characters/Heroes/Ability.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Ability.cpp.i
.PHONY : Game/Characters/Heroes/Ability.cpp.i

Game/Characters/Heroes/Ability.s: Game/Characters/Heroes/Ability.cpp.s

.PHONY : Game/Characters/Heroes/Ability.s

# target to generate assembly for a file
Game/Characters/Heroes/Ability.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Ability.cpp.s
.PHONY : Game/Characters/Heroes/Ability.cpp.s

Game/Characters/Heroes/Hero.o: Game/Characters/Heroes/Hero.cpp.o

.PHONY : Game/Characters/Heroes/Hero.o

# target to build an object file
Game/Characters/Heroes/Hero.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Hero.cpp.o
.PHONY : Game/Characters/Heroes/Hero.cpp.o

Game/Characters/Heroes/Hero.i: Game/Characters/Heroes/Hero.cpp.i

.PHONY : Game/Characters/Heroes/Hero.i

# target to preprocess a source file
Game/Characters/Heroes/Hero.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Hero.cpp.i
.PHONY : Game/Characters/Heroes/Hero.cpp.i

Game/Characters/Heroes/Hero.s: Game/Characters/Heroes/Hero.cpp.s

.PHONY : Game/Characters/Heroes/Hero.s

# target to generate assembly for a file
Game/Characters/Heroes/Hero.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Hero.cpp.s
.PHONY : Game/Characters/Heroes/Hero.cpp.s

Game/Characters/Heroes/HeroFactory.o: Game/Characters/Heroes/HeroFactory.cpp.o

.PHONY : Game/Characters/Heroes/HeroFactory.o

# target to build an object file
Game/Characters/Heroes/HeroFactory.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/HeroFactory.cpp.o
.PHONY : Game/Characters/Heroes/HeroFactory.cpp.o

Game/Characters/Heroes/HeroFactory.i: Game/Characters/Heroes/HeroFactory.cpp.i

.PHONY : Game/Characters/Heroes/HeroFactory.i

# target to preprocess a source file
Game/Characters/Heroes/HeroFactory.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/HeroFactory.cpp.i
.PHONY : Game/Characters/Heroes/HeroFactory.cpp.i

Game/Characters/Heroes/HeroFactory.s: Game/Characters/Heroes/HeroFactory.cpp.s

.PHONY : Game/Characters/Heroes/HeroFactory.s

# target to generate assembly for a file
Game/Characters/Heroes/HeroFactory.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/HeroFactory.cpp.s
.PHONY : Game/Characters/Heroes/HeroFactory.cpp.s

Game/Characters/Heroes/Knight/Execute.o: Game/Characters/Heroes/Knight/Execute.cpp.o

.PHONY : Game/Characters/Heroes/Knight/Execute.o

# target to build an object file
Game/Characters/Heroes/Knight/Execute.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Execute.cpp.o
.PHONY : Game/Characters/Heroes/Knight/Execute.cpp.o

Game/Characters/Heroes/Knight/Execute.i: Game/Characters/Heroes/Knight/Execute.cpp.i

.PHONY : Game/Characters/Heroes/Knight/Execute.i

# target to preprocess a source file
Game/Characters/Heroes/Knight/Execute.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Execute.cpp.i
.PHONY : Game/Characters/Heroes/Knight/Execute.cpp.i

Game/Characters/Heroes/Knight/Execute.s: Game/Characters/Heroes/Knight/Execute.cpp.s

.PHONY : Game/Characters/Heroes/Knight/Execute.s

# target to generate assembly for a file
Game/Characters/Heroes/Knight/Execute.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Execute.cpp.s
.PHONY : Game/Characters/Heroes/Knight/Execute.cpp.s

Game/Characters/Heroes/Knight/Knight.o: Game/Characters/Heroes/Knight/Knight.cpp.o

.PHONY : Game/Characters/Heroes/Knight/Knight.o

# target to build an object file
Game/Characters/Heroes/Knight/Knight.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Knight.cpp.o
.PHONY : Game/Characters/Heroes/Knight/Knight.cpp.o

Game/Characters/Heroes/Knight/Knight.i: Game/Characters/Heroes/Knight/Knight.cpp.i

.PHONY : Game/Characters/Heroes/Knight/Knight.i

# target to preprocess a source file
Game/Characters/Heroes/Knight/Knight.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Knight.cpp.i
.PHONY : Game/Characters/Heroes/Knight/Knight.cpp.i

Game/Characters/Heroes/Knight/Knight.s: Game/Characters/Heroes/Knight/Knight.cpp.s

.PHONY : Game/Characters/Heroes/Knight/Knight.s

# target to generate assembly for a file
Game/Characters/Heroes/Knight/Knight.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Knight.cpp.s
.PHONY : Game/Characters/Heroes/Knight/Knight.cpp.s

Game/Characters/Heroes/Knight/Slam.o: Game/Characters/Heroes/Knight/Slam.cpp.o

.PHONY : Game/Characters/Heroes/Knight/Slam.o

# target to build an object file
Game/Characters/Heroes/Knight/Slam.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Slam.cpp.o
.PHONY : Game/Characters/Heroes/Knight/Slam.cpp.o

Game/Characters/Heroes/Knight/Slam.i: Game/Characters/Heroes/Knight/Slam.cpp.i

.PHONY : Game/Characters/Heroes/Knight/Slam.i

# target to preprocess a source file
Game/Characters/Heroes/Knight/Slam.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Slam.cpp.i
.PHONY : Game/Characters/Heroes/Knight/Slam.cpp.i

Game/Characters/Heroes/Knight/Slam.s: Game/Characters/Heroes/Knight/Slam.cpp.s

.PHONY : Game/Characters/Heroes/Knight/Slam.s

# target to generate assembly for a file
Game/Characters/Heroes/Knight/Slam.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Knight/Slam.cpp.s
.PHONY : Game/Characters/Heroes/Knight/Slam.cpp.s

Game/Characters/Heroes/Pyromancer/Fireblast.o: Game/Characters/Heroes/Pyromancer/Fireblast.cpp.o

.PHONY : Game/Characters/Heroes/Pyromancer/Fireblast.o

# target to build an object file
Game/Characters/Heroes/Pyromancer/Fireblast.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Fireblast.cpp.o
.PHONY : Game/Characters/Heroes/Pyromancer/Fireblast.cpp.o

Game/Characters/Heroes/Pyromancer/Fireblast.i: Game/Characters/Heroes/Pyromancer/Fireblast.cpp.i

.PHONY : Game/Characters/Heroes/Pyromancer/Fireblast.i

# target to preprocess a source file
Game/Characters/Heroes/Pyromancer/Fireblast.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Fireblast.cpp.i
.PHONY : Game/Characters/Heroes/Pyromancer/Fireblast.cpp.i

Game/Characters/Heroes/Pyromancer/Fireblast.s: Game/Characters/Heroes/Pyromancer/Fireblast.cpp.s

.PHONY : Game/Characters/Heroes/Pyromancer/Fireblast.s

# target to generate assembly for a file
Game/Characters/Heroes/Pyromancer/Fireblast.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Fireblast.cpp.s
.PHONY : Game/Characters/Heroes/Pyromancer/Fireblast.cpp.s

Game/Characters/Heroes/Pyromancer/Ignite.o: Game/Characters/Heroes/Pyromancer/Ignite.cpp.o

.PHONY : Game/Characters/Heroes/Pyromancer/Ignite.o

# target to build an object file
Game/Characters/Heroes/Pyromancer/Ignite.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Ignite.cpp.o
.PHONY : Game/Characters/Heroes/Pyromancer/Ignite.cpp.o

Game/Characters/Heroes/Pyromancer/Ignite.i: Game/Characters/Heroes/Pyromancer/Ignite.cpp.i

.PHONY : Game/Characters/Heroes/Pyromancer/Ignite.i

# target to preprocess a source file
Game/Characters/Heroes/Pyromancer/Ignite.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Ignite.cpp.i
.PHONY : Game/Characters/Heroes/Pyromancer/Ignite.cpp.i

Game/Characters/Heroes/Pyromancer/Ignite.s: Game/Characters/Heroes/Pyromancer/Ignite.cpp.s

.PHONY : Game/Characters/Heroes/Pyromancer/Ignite.s

# target to generate assembly for a file
Game/Characters/Heroes/Pyromancer/Ignite.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Ignite.cpp.s
.PHONY : Game/Characters/Heroes/Pyromancer/Ignite.cpp.s

Game/Characters/Heroes/Pyromancer/Pyromancer.o: Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.o

.PHONY : Game/Characters/Heroes/Pyromancer/Pyromancer.o

# target to build an object file
Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.o
.PHONY : Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.o

Game/Characters/Heroes/Pyromancer/Pyromancer.i: Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.i

.PHONY : Game/Characters/Heroes/Pyromancer/Pyromancer.i

# target to preprocess a source file
Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.i
.PHONY : Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.i

Game/Characters/Heroes/Pyromancer/Pyromancer.s: Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.s

.PHONY : Game/Characters/Heroes/Pyromancer/Pyromancer.s

# target to generate assembly for a file
Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.s
.PHONY : Game/Characters/Heroes/Pyromancer/Pyromancer.cpp.s

Game/Characters/Heroes/Rogue/Backstab.o: Game/Characters/Heroes/Rogue/Backstab.cpp.o

.PHONY : Game/Characters/Heroes/Rogue/Backstab.o

# target to build an object file
Game/Characters/Heroes/Rogue/Backstab.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Backstab.cpp.o
.PHONY : Game/Characters/Heroes/Rogue/Backstab.cpp.o

Game/Characters/Heroes/Rogue/Backstab.i: Game/Characters/Heroes/Rogue/Backstab.cpp.i

.PHONY : Game/Characters/Heroes/Rogue/Backstab.i

# target to preprocess a source file
Game/Characters/Heroes/Rogue/Backstab.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Backstab.cpp.i
.PHONY : Game/Characters/Heroes/Rogue/Backstab.cpp.i

Game/Characters/Heroes/Rogue/Backstab.s: Game/Characters/Heroes/Rogue/Backstab.cpp.s

.PHONY : Game/Characters/Heroes/Rogue/Backstab.s

# target to generate assembly for a file
Game/Characters/Heroes/Rogue/Backstab.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Backstab.cpp.s
.PHONY : Game/Characters/Heroes/Rogue/Backstab.cpp.s

Game/Characters/Heroes/Rogue/Paralysis.o: Game/Characters/Heroes/Rogue/Paralysis.cpp.o

.PHONY : Game/Characters/Heroes/Rogue/Paralysis.o

# target to build an object file
Game/Characters/Heroes/Rogue/Paralysis.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Paralysis.cpp.o
.PHONY : Game/Characters/Heroes/Rogue/Paralysis.cpp.o

Game/Characters/Heroes/Rogue/Paralysis.i: Game/Characters/Heroes/Rogue/Paralysis.cpp.i

.PHONY : Game/Characters/Heroes/Rogue/Paralysis.i

# target to preprocess a source file
Game/Characters/Heroes/Rogue/Paralysis.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Paralysis.cpp.i
.PHONY : Game/Characters/Heroes/Rogue/Paralysis.cpp.i

Game/Characters/Heroes/Rogue/Paralysis.s: Game/Characters/Heroes/Rogue/Paralysis.cpp.s

.PHONY : Game/Characters/Heroes/Rogue/Paralysis.s

# target to generate assembly for a file
Game/Characters/Heroes/Rogue/Paralysis.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Paralysis.cpp.s
.PHONY : Game/Characters/Heroes/Rogue/Paralysis.cpp.s

Game/Characters/Heroes/Rogue/Rogue.o: Game/Characters/Heroes/Rogue/Rogue.cpp.o

.PHONY : Game/Characters/Heroes/Rogue/Rogue.o

# target to build an object file
Game/Characters/Heroes/Rogue/Rogue.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Rogue.cpp.o
.PHONY : Game/Characters/Heroes/Rogue/Rogue.cpp.o

Game/Characters/Heroes/Rogue/Rogue.i: Game/Characters/Heroes/Rogue/Rogue.cpp.i

.PHONY : Game/Characters/Heroes/Rogue/Rogue.i

# target to preprocess a source file
Game/Characters/Heroes/Rogue/Rogue.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Rogue.cpp.i
.PHONY : Game/Characters/Heroes/Rogue/Rogue.cpp.i

Game/Characters/Heroes/Rogue/Rogue.s: Game/Characters/Heroes/Rogue/Rogue.cpp.s

.PHONY : Game/Characters/Heroes/Rogue/Rogue.s

# target to generate assembly for a file
Game/Characters/Heroes/Rogue/Rogue.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Rogue/Rogue.cpp.s
.PHONY : Game/Characters/Heroes/Rogue/Rogue.cpp.s

Game/Characters/Heroes/Wizard/Deflect.o: Game/Characters/Heroes/Wizard/Deflect.cpp.o

.PHONY : Game/Characters/Heroes/Wizard/Deflect.o

# target to build an object file
Game/Characters/Heroes/Wizard/Deflect.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Deflect.cpp.o
.PHONY : Game/Characters/Heroes/Wizard/Deflect.cpp.o

Game/Characters/Heroes/Wizard/Deflect.i: Game/Characters/Heroes/Wizard/Deflect.cpp.i

.PHONY : Game/Characters/Heroes/Wizard/Deflect.i

# target to preprocess a source file
Game/Characters/Heroes/Wizard/Deflect.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Deflect.cpp.i
.PHONY : Game/Characters/Heroes/Wizard/Deflect.cpp.i

Game/Characters/Heroes/Wizard/Deflect.s: Game/Characters/Heroes/Wizard/Deflect.cpp.s

.PHONY : Game/Characters/Heroes/Wizard/Deflect.s

# target to generate assembly for a file
Game/Characters/Heroes/Wizard/Deflect.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Deflect.cpp.s
.PHONY : Game/Characters/Heroes/Wizard/Deflect.cpp.s

Game/Characters/Heroes/Wizard/Drain.o: Game/Characters/Heroes/Wizard/Drain.cpp.o

.PHONY : Game/Characters/Heroes/Wizard/Drain.o

# target to build an object file
Game/Characters/Heroes/Wizard/Drain.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Drain.cpp.o
.PHONY : Game/Characters/Heroes/Wizard/Drain.cpp.o

Game/Characters/Heroes/Wizard/Drain.i: Game/Characters/Heroes/Wizard/Drain.cpp.i

.PHONY : Game/Characters/Heroes/Wizard/Drain.i

# target to preprocess a source file
Game/Characters/Heroes/Wizard/Drain.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Drain.cpp.i
.PHONY : Game/Characters/Heroes/Wizard/Drain.cpp.i

Game/Characters/Heroes/Wizard/Drain.s: Game/Characters/Heroes/Wizard/Drain.cpp.s

.PHONY : Game/Characters/Heroes/Wizard/Drain.s

# target to generate assembly for a file
Game/Characters/Heroes/Wizard/Drain.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Drain.cpp.s
.PHONY : Game/Characters/Heroes/Wizard/Drain.cpp.s

Game/Characters/Heroes/Wizard/Wizard.o: Game/Characters/Heroes/Wizard/Wizard.cpp.o

.PHONY : Game/Characters/Heroes/Wizard/Wizard.o

# target to build an object file
Game/Characters/Heroes/Wizard/Wizard.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Wizard.cpp.o
.PHONY : Game/Characters/Heroes/Wizard/Wizard.cpp.o

Game/Characters/Heroes/Wizard/Wizard.i: Game/Characters/Heroes/Wizard/Wizard.cpp.i

.PHONY : Game/Characters/Heroes/Wizard/Wizard.i

# target to preprocess a source file
Game/Characters/Heroes/Wizard/Wizard.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Wizard.cpp.i
.PHONY : Game/Characters/Heroes/Wizard/Wizard.cpp.i

Game/Characters/Heroes/Wizard/Wizard.s: Game/Characters/Heroes/Wizard/Wizard.cpp.s

.PHONY : Game/Characters/Heroes/Wizard/Wizard.s

# target to generate assembly for a file
Game/Characters/Heroes/Wizard/Wizard.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Characters/Heroes/Wizard/Wizard.cpp.s
.PHONY : Game/Characters/Heroes/Wizard/Wizard.cpp.s

Game/Game.o: Game/Game.cpp.o

.PHONY : Game/Game.o

# target to build an object file
Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Game.cpp.o
.PHONY : Game/Game.cpp.o

Game/Game.i: Game/Game.cpp.i

.PHONY : Game/Game.i

# target to preprocess a source file
Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Game.cpp.i
.PHONY : Game/Game.cpp.i

Game/Game.s: Game/Game.cpp.s

.PHONY : Game/Game.s

# target to generate assembly for a file
Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Game.cpp.s
.PHONY : Game/Game.cpp.s

Game/Map/Map.o: Game/Map/Map.cpp.o

.PHONY : Game/Map/Map.o

# target to build an object file
Game/Map/Map.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Map/Map.cpp.o
.PHONY : Game/Map/Map.cpp.o

Game/Map/Map.i: Game/Map/Map.cpp.i

.PHONY : Game/Map/Map.i

# target to preprocess a source file
Game/Map/Map.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Map/Map.cpp.i
.PHONY : Game/Map/Map.cpp.i

Game/Map/Map.s: Game/Map/Map.cpp.s

.PHONY : Game/Map/Map.s

# target to generate assembly for a file
Game/Map/Map.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/Game/Map/Map.cpp.s
.PHONY : Game/Map/Map.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/LOOP.dir/build.make CMakeFiles/LOOP.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... LOOP"
	@echo "... edit_cache"
	@echo "... Game/Characters/Attributes/Coords.o"
	@echo "... Game/Characters/Attributes/Coords.i"
	@echo "... Game/Characters/Attributes/Coords.s"
	@echo "... Game/Characters/Attributes/Effects.o"
	@echo "... Game/Characters/Attributes/Effects.i"
	@echo "... Game/Characters/Attributes/Effects.s"
	@echo "... Game/Characters/Attributes/Stats.o"
	@echo "... Game/Characters/Attributes/Stats.i"
	@echo "... Game/Characters/Attributes/Stats.s"
	@echo "... Game/Characters/Attributes/Strategy.o"
	@echo "... Game/Characters/Attributes/Strategy.i"
	@echo "... Game/Characters/Attributes/Strategy.s"
	@echo "... Game/Characters/Heroes/Ability.o"
	@echo "... Game/Characters/Heroes/Ability.i"
	@echo "... Game/Characters/Heroes/Ability.s"
	@echo "... Game/Characters/Heroes/Hero.o"
	@echo "... Game/Characters/Heroes/Hero.i"
	@echo "... Game/Characters/Heroes/Hero.s"
	@echo "... Game/Characters/Heroes/HeroFactory.o"
	@echo "... Game/Characters/Heroes/HeroFactory.i"
	@echo "... Game/Characters/Heroes/HeroFactory.s"
	@echo "... Game/Characters/Heroes/Knight/Execute.o"
	@echo "... Game/Characters/Heroes/Knight/Execute.i"
	@echo "... Game/Characters/Heroes/Knight/Execute.s"
	@echo "... Game/Characters/Heroes/Knight/Knight.o"
	@echo "... Game/Characters/Heroes/Knight/Knight.i"
	@echo "... Game/Characters/Heroes/Knight/Knight.s"
	@echo "... Game/Characters/Heroes/Knight/Slam.o"
	@echo "... Game/Characters/Heroes/Knight/Slam.i"
	@echo "... Game/Characters/Heroes/Knight/Slam.s"
	@echo "... Game/Characters/Heroes/Pyromancer/Fireblast.o"
	@echo "... Game/Characters/Heroes/Pyromancer/Fireblast.i"
	@echo "... Game/Characters/Heroes/Pyromancer/Fireblast.s"
	@echo "... Game/Characters/Heroes/Pyromancer/Ignite.o"
	@echo "... Game/Characters/Heroes/Pyromancer/Ignite.i"
	@echo "... Game/Characters/Heroes/Pyromancer/Ignite.s"
	@echo "... Game/Characters/Heroes/Pyromancer/Pyromancer.o"
	@echo "... Game/Characters/Heroes/Pyromancer/Pyromancer.i"
	@echo "... Game/Characters/Heroes/Pyromancer/Pyromancer.s"
	@echo "... Game/Characters/Heroes/Rogue/Backstab.o"
	@echo "... Game/Characters/Heroes/Rogue/Backstab.i"
	@echo "... Game/Characters/Heroes/Rogue/Backstab.s"
	@echo "... Game/Characters/Heroes/Rogue/Paralysis.o"
	@echo "... Game/Characters/Heroes/Rogue/Paralysis.i"
	@echo "... Game/Characters/Heroes/Rogue/Paralysis.s"
	@echo "... Game/Characters/Heroes/Rogue/Rogue.o"
	@echo "... Game/Characters/Heroes/Rogue/Rogue.i"
	@echo "... Game/Characters/Heroes/Rogue/Rogue.s"
	@echo "... Game/Characters/Heroes/Wizard/Deflect.o"
	@echo "... Game/Characters/Heroes/Wizard/Deflect.i"
	@echo "... Game/Characters/Heroes/Wizard/Deflect.s"
	@echo "... Game/Characters/Heroes/Wizard/Drain.o"
	@echo "... Game/Characters/Heroes/Wizard/Drain.i"
	@echo "... Game/Characters/Heroes/Wizard/Drain.s"
	@echo "... Game/Characters/Heroes/Wizard/Wizard.o"
	@echo "... Game/Characters/Heroes/Wizard/Wizard.i"
	@echo "... Game/Characters/Heroes/Wizard/Wizard.s"
	@echo "... Game/Game.o"
	@echo "... Game/Game.i"
	@echo "... Game/Game.s"
	@echo "... Game/Map/Map.o"
	@echo "... Game/Map/Map.i"
	@echo "... Game/Map/Map.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

